// <auto-generated />
using System;
using EscalaMensal.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscalaMensal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822014743_AdicionandoFuncoesRestantes")]
    partial class AdicionandoFuncoesRestantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscalaMensal.Domain.Entities.CargoNivelFuncaoPermitida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("Cargo", "Nivel", "FuncaoId")
                        .IsUnique();

                    b.ToTable("CargoNivelFuncaoPermitidas");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Funcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("NivelMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviacao = "CG",
                            Cargo = 2,
                            NivelMinimo = 3,
                            Nome = "Cerimoniário Geral"
                        },
                        new
                        {
                            Id = 2,
                            Abreviacao = "CA1",
                            Cargo = 2,
                            NivelMinimo = 1,
                            Nome = "Cerimoniário Auxiliar 1"
                        },
                        new
                        {
                            Id = 3,
                            Abreviacao = "CA2",
                            Cargo = 2,
                            NivelMinimo = 1,
                            Nome = "Cerimoniário Auxiliar 2"
                        },
                        new
                        {
                            Id = 4,
                            Abreviacao = "Li",
                            Cargo = 2,
                            NivelMinimo = 3,
                            Nome = "Librífero"
                        },
                        new
                        {
                            Id = 5,
                            Abreviacao = "L",
                            Cargo = 1,
                            NivelMinimo = 2,
                            Nome = "Leitor"
                        },
                        new
                        {
                            Id = 6,
                            Abreviacao = "Ce1",
                            Cargo = 1,
                            NivelMinimo = 3,
                            Nome = "Ceroferario 1"
                        },
                        new
                        {
                            Id = 7,
                            Abreviacao = "Ce2",
                            Cargo = 1,
                            NivelMinimo = 3,
                            Nome = "Ceroferario 2"
                        },
                        new
                        {
                            Id = 8,
                            Abreviacao = "Cr",
                            Cargo = 1,
                            NivelMinimo = 2,
                            Nome = "Cruciferário"
                        },
                        new
                        {
                            Id = 9,
                            Abreviacao = "O",
                            Cargo = 1,
                            NivelMinimo = 1,
                            Nome = "Ofertório"
                        },
                        new
                        {
                            Id = 10,
                            Abreviacao = "T",
                            Cargo = 2,
                            NivelMinimo = 2,
                            Nome = "Turibulo"
                        },
                        new
                        {
                            Id = 11,
                            Abreviacao = "N",
                            Cargo = 1,
                            NivelMinimo = 1,
                            Nome = "Naveta"
                        },
                        new
                        {
                            Id = 12,
                            Abreviacao = "CP",
                            Cargo = 2,
                            NivelMinimo = 1,
                            Nome = "Cerimoniário de Procissão"
                        });
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricosEscala");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.ItemEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ItensEscala");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Restricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Restricoes");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioVinculadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioVinculadoId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cargo = 2,
                            Nivel = 3,
                            Nome = "João"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = false,
                            Cargo = 1,
                            Nivel = 1,
                            Nome = "Maria"
                        });
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.CargoNivelFuncaoPermitida", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoEscala", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscalaMensal.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.ItemEscala", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Escala", "Escala")
                        .WithMany("Itens")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaMensal.Domain.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscalaMensal.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Escala");

                    b.Navigation("Funcao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Restricao", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Restricoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Usuario", "UsuarioVinculado")
                        .WithMany()
                        .HasForeignKey("UsuarioVinculadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioVinculado");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Escala", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Restricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
