// <auto-generated />
using System;
using EscalaMensal.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscalaMensal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903014619_RenameUsuarioToMembro")]
    partial class RenameUsuarioToMembro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscalaMensal.Domain.Entities.CargoNivelFuncaoPermitida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("Cargo", "Nivel", "FuncaoId")
                        .IsUnique();

                    b.ToTable("CargoNivelFuncaoPermitidas");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Configuracao", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Chave");

                    b.ToTable("Configuracoes");

                    b.HasData(
                        new
                        {
                            Chave = "MaxNivel",
                            Valor = "3"
                        });
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<int>("LimitePermitido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Funcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<bool>("EhMultipla")
                        .HasColumnType("bit");

                    b.Property<int>("NivelMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrigatoria")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Funcoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviacao = "CG",
                            Cargo = 2,
                            EhMultipla = false,
                            NivelMinimo = 3,
                            Nome = "Cerimoniário Geral",
                            Obrigatoria = true
                        },
                        new
                        {
                            Id = 2,
                            Abreviacao = "CA1",
                            Cargo = 2,
                            EhMultipla = false,
                            NivelMinimo = 1,
                            Nome = "Cerimoniário Auxiliar 1",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 3,
                            Abreviacao = "CA2",
                            Cargo = 2,
                            EhMultipla = false,
                            NivelMinimo = 1,
                            Nome = "Cerimoniário Auxiliar 2",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 4,
                            Abreviacao = "Li",
                            Cargo = 2,
                            EhMultipla = false,
                            NivelMinimo = 3,
                            Nome = "Librífero",
                            Obrigatoria = true
                        },
                        new
                        {
                            Id = 5,
                            Abreviacao = "L",
                            Cargo = 1,
                            EhMultipla = false,
                            NivelMinimo = 2,
                            Nome = "Leitor",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 6,
                            Abreviacao = "Ce",
                            Cargo = 1,
                            EhMultipla = false,
                            NivelMinimo = 3,
                            Nome = "Ceroferário",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 8,
                            Abreviacao = "Cr",
                            Cargo = 1,
                            EhMultipla = false,
                            NivelMinimo = 2,
                            Nome = "Cruciferário",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 9,
                            Abreviacao = "O",
                            Cargo = 1,
                            EhMultipla = false,
                            NivelMinimo = 1,
                            Nome = "Ofertório",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 10,
                            Abreviacao = "T",
                            Cargo = 2,
                            EhMultipla = false,
                            NivelMinimo = 2,
                            Nome = "Turibulo",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 11,
                            Abreviacao = "N",
                            Cargo = 1,
                            EhMultipla = false,
                            NivelMinimo = 1,
                            Nome = "Naveta",
                            Obrigatoria = false
                        },
                        new
                        {
                            Id = 12,
                            Abreviacao = "CP",
                            Cargo = 2,
                            EhMultipla = false,
                            NivelMinimo = 1,
                            Nome = "Cerimoniário de Procissão",
                            Obrigatoria = false
                        });
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<int>("EscalaOriginalId")
                        .HasColumnType("int");

                    b.Property<int>("LimitePermitido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricosEscala");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoItemMissa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FuncaoAbreviacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<string>("FuncaoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HistoricoMissaId")
                        .HasColumnType("int");

                    b.Property<int>("ItemMissaOriginalId")
                        .HasColumnType("int");

                    b.Property<int?>("MembroId")
                        .HasColumnType("int");

                    b.Property<string>("MembroNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("HistoricoMissaId");

                    b.HasIndex("MembroId");

                    b.ToTable("HistoricosItemMissa");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoMissa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<int>("HistoricoEscalaId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("MissaOriginalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoricoEscalaId");

                    b.ToTable("HistoricosMissa");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HorarioFixo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("HorariosFixos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Horario = new TimeOnly(7, 30, 0)
                        },
                        new
                        {
                            Id = 2,
                            Horario = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Horario = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Horario = new TimeOnly(19, 0, 0)
                        });
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.ItemMissa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<int?>("MembroId")
                        .HasColumnType("int");

                    b.Property<int>("MissaId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("MembroId");

                    b.HasIndex("MissaId");

                    b.ToTable("ItensMissa");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("DiasDisponiveisRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiasEscalados")
                        .HasColumnType("int");

                    b.Property<string>("HorasPreferenciaisRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MembroVinculadoId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MembroVinculadoId");

                    b.ToTable("Membros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cargo = 2,
                            DiasDisponiveisRaw = "Saturday",
                            HorasPreferenciaisRaw = "10:00",
                            Nivel = 3,
                            Nome = "João"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = false,
                            Cargo = 2,
                            DiasDisponiveisRaw = "Wednesday,Thursday,Saturday",
                            HorasPreferenciaisRaw = "07:30",
                            Nivel = 2,
                            Nome = "Pedro"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = false,
                            Cargo = 2,
                            DiasDisponiveisRaw = "Wednesday,Thursday,Saturday",
                            HorasPreferenciaisRaw = "07:30",
                            Nivel = 2,
                            Nome = "Anna"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = false,
                            Cargo = 1,
                            DiasDisponiveisRaw = "Wednesday,Thursday,Saturday",
                            HorasPreferenciaisRaw = "07:30",
                            Nivel = 1,
                            Nome = "Maria"
                        });
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.MissaPadrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CriarFuncoesPadrao")
                        .HasColumnType("bit");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("MissasPadrao");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Missas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.ToTable("Missas");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Restricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.ToTable("Restricoes");
                });

            modelBuilder.Entity("FuncaoMissaPadrao", b =>
                {
                    b.Property<int>("FuncoesId")
                        .HasColumnType("int");

                    b.Property<int>("MissaPadraoId")
                        .HasColumnType("int");

                    b.HasKey("FuncoesId", "MissaPadraoId");

                    b.HasIndex("MissaPadraoId");

                    b.ToTable("FuncaoMissaPadrao");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.CargoNivelFuncaoPermitida", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoItemMissa", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscalaMensal.Domain.Entities.HistoricoMissa", "HistoricoMissa")
                        .WithMany("HistoricoItensMissa")
                        .HasForeignKey("HistoricoMissaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaMensal.Domain.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Funcao");

                    b.Navigation("HistoricoMissa");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoMissa", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.HistoricoEscala", "HistoricoEscala")
                        .WithMany("HistoricoMissas")
                        .HasForeignKey("HistoricoEscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricoEscala");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.ItemMissa", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaMensal.Domain.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EscalaMensal.Domain.Entities.Missas", "Missa")
                        .WithMany("ItensMissa")
                        .HasForeignKey("MissaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Membro");

                    b.Navigation("Missa");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Membro", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Membro", "MembroVinculado")
                        .WithMany()
                        .HasForeignKey("MembroVinculadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MembroVinculado");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Missas", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Escala", "Escala")
                        .WithMany("Missas")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Restricao", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Membro", "Membro")
                        .WithMany("Restricoes")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FuncaoMissaPadrao", b =>
                {
                    b.HasOne("EscalaMensal.Domain.Entities.Funcao", null)
                        .WithMany()
                        .HasForeignKey("FuncoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaMensal.Domain.Entities.MissaPadrao", null)
                        .WithMany()
                        .HasForeignKey("MissaPadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Escala", b =>
                {
                    b.Navigation("Missas");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoEscala", b =>
                {
                    b.Navigation("HistoricoMissas");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.HistoricoMissa", b =>
                {
                    b.Navigation("HistoricoItensMissa");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Membro", b =>
                {
                    b.Navigation("Restricoes");
                });

            modelBuilder.Entity("EscalaMensal.Domain.Entities.Missas", b =>
                {
                    b.Navigation("ItensMissa");
                });
#pragma warning restore 612, 618
        }
    }
}
